### ISSUE TITLE
Bug in the landing page

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#100]
### Description
The upper border hides behind some div!

### Screenshots/testimonials

![Screenshot from 2020-09-27 01-14-28](https://user-images.githubusercontent.com/48787278/94349250-64a00080-0060-11eb-9032-5f7a22080570.png)

**Comment by LogMoss** [comment]
Can you assign it to me, I have the fix.

**Comment by EmperorYP7** [comment]
Go ahead!
