### ISSUE TITLE
The fixed HG logo on the top can be given some padding

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#102]
N/A

**Comment by LogMoss** [comment]
Can assign this to me also?

**Comment by shubhamgoel24** [comment]
Can i work on this issue ?

**Comment by EmperorYP7** [comment]
We won't be assigning this to anyone. You all may proceed with this.

**Comment by SaravgiYash** [comment]
@EmperorYP7 I have made some changes and created a PR.

**Comment by ankiiitraj** [comment]
> @EmperorYP7 I have made some changes and created a PR.

@Yashs911 Thanks for the PR, meanwhile we review, check out more issues!

**Comment by ankiiitraj** [comment]
closing against #104
