### ISSUE TITLE
Pagination in the events component

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#107]
### Description
As we'll be showing all the events on the Events page.
Pagination will be very helpful!

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by tusharjain0022** [comment]
Suggestion : I've a basic layout structure for the event component where details of all the events are to be displayed so that everything looks well organized.
Note - It's just a blueprint so color is set to default and structure is just for reference.

![event-page](https://user-images.githubusercontent.com/59157988/94360044-3e15b000-00c8-11eb-8ba1-12e548a2e2d4.png)

**Comment by ankiiitraj** [comment]
This looks cool @hariom1625 @EmperorYP7 check this out!

**Comment by EmperorYP7** [comment]
That's great!🤩 You just need to design it well now..

**Comment by hariom1625** [comment]
Layout looks great, just need the design now to get started !!

**Comment by tusharjain0022** [comment]
Alright I'll try to design a finished look to this layout in accordance with the current theme.

**Comment by tusharjain0022** [comment]
# 1 
![event](https://user-images.githubusercontent.com/59157988/94375792-dbf29480-0133-11eb-89ee-ad2cdbd6af26.png)

# 2
![event-without_sat](https://user-images.githubusercontent.com/59157988/94375801-e6149300-0133-11eb-959e-4e66c3ac9817.png)

# 3
![event(1)](https://user-images.githubusercontent.com/59157988/94375811-ed3ba100-0133-11eb-8155-bba818f9998d.png)

# 4
![event(2)](https://user-images.githubusercontent.com/59157988/94375816-f3318200-0133-11eb-917a-65942e835e02.png)

**Comment by hariom1625** [comment]
Great work, In the design (4) it gives an illusion that the table is floating in the space, that looks amazing !!
Can we adjust the Important posters section somewhere else other than the right side?

**Comment by ankiiitraj** [comment]
So we can start with making the events page.
Go ahead and open relevant issues for the same with the proposed design
Well done @tusharjain0022

**Comment by tusharjain0022** [comment]
> Great work, In the design (4) it gives an illusion that the table is floating in the space, that looks amazing !!
> Can we adjust the Important posters section somewhere else other than the right side?

I tried adjusting the poster section somewhere on the page but it seems to over populate the page so I just removed it in the last design(4) so that everything looks simple and nice. Suggestions are welcome.

**Comment by EmperorYP7** [comment]
Great work on the designs @tusharjain0022 :fire: I think we should go for design 4.

**Comment by tusharjain0022** [comment]
I think we'll be required a separate Event component for this , and current event component needed to be shifted to `Home` folder. Just like we're having two different components for sponsors.
What you say @EmperorYP7 @ankiiitraj @hariom1625

**Comment by EmperorYP7** [comment]
Yes. Thats the way we should be doing it anyways.

**Comment by ankiiitraj** [comment]
> I think we'll be required a separate Event component for this , and current event component needed to be shifted to `Home` folder. Just like we're having two different components for sponsors.
> What you say @EmperorYP7 @ankiiitraj @hariom1625

This sounds good to me!
PS: attach PR to some issue!
