### ISSUE TITLE
Events page mobile view bug

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#108]
### Description
`Event` hides behind the hamburger icon.
Checkout screenshot attached

### Screenshots/testimonials

![Screenshot from 2020-09-27 13-57-27](https://user-images.githubusercontent.com/48787278/94360214-67830b80-00c9-11eb-8c01-ef4d2c980459.png)

**Comment by NiketanG** [comment]
I could fix this

**Comment by ankiiitraj** [comment]
Go for it @NiketanG

**Comment by NiketanG** [comment]
@ankiiitraj PR is up #149

**Comment by hariom1625** [comment]
The Centering of the event header had affected the content of the event section. It doesn't look good to me.
![Screenshot (181)](https://user-images.githubusercontent.com/66957239/94943655-acf26f00-04f5-11eb-8746-5dd13c923fb5.png)

**Comment by ankiiitraj** [comment]
completely missed that! @NiketanG Can you fix it in your next PR

**Comment by hariom1625** [comment]
A lot of blank space is being generated below the footer on the EVENTS Page.
For screen resolution less than 853px.
![Screenshot (183)](https://user-images.githubusercontent.com/66957239/94946114-4a9b6d80-04f9-11eb-87e6-cfbafb01ee9e.png)

**Comment by NiketanG** [comment]
> The Centering of the event header had affected the content of the event section. It doesn't look good to me.
> ![Screenshot (181)](https://user-images.githubusercontent.com/66957239/94943655-acf26f00-04f5-11eb-8746-5dd13c923fb5.png)

The content should be on the right and only the title should be centered. i.e "Receiving signals..." text shouldn't be centered. That's it, right ?

**Comment by hariom1625** [comment]
Yes @NiketanG, make the event content left-aligned as displayed in the image below
![Screenshot (184)](https://user-images.githubusercontent.com/66957239/94948476-04480d80-04fd-11eb-9c1b-758112f9ef89.png)

And you can also try to fix the footer issue in the Events Page mentioned here as well in your next commit. Will that be fine?

**Comment by NiketanG** [comment]
> Yes @NiketanG, make the event content left-aligned as displayed in the image below

Okayyy

> And you can also try to fix the footer issue in the Events Page mentioned here as well in your next commit. Will that be fine?

Sure. Although, I might have to rewrite the styling for Events page using better techniques like Flexbox. It's using margins to align stuff which is the cause. Is that fine ?

**Comment by hariom1625** [comment]
Yes go ahead, and have a look at all the files before starting, you will notice that the Event component that is being rendered on the Home page is the same and is being reused and rendered on the Event page. So, while implementing just be careful as the dynamics of both the pages are a bit different :-)
And always define a New className to all the new div tags and components you will declare so as to avoid irregular rendering of the components and also avoid the use of inline and internal CSS :-)
