### ISSUE TITLE
Navbar links not updating their state with the change in URL

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/hg#109]
### Description
<write your description>Navbar links are not changing their state in accordance with the change in URL. Refer to the Screenshot attached below , page is in home section while navbar menu is showing Event as active component.
Note : This happens when we press Back button on the browser or phone .

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

![House of Geeks, IIIT Ranchi - Google Chrome 2020-09-27 22-28-56_Trim (1)](https://user-images.githubusercontent.com/59157988/94371111-9b821f00-0111-11eb-998f-e718dcff48e1.gif)

**Comment by RishavMz** [comment]
Currently the navbar is a function component which is using hooks, so component cannot be reloaded by making a state change. 
However, a simple solution would be to reload the screen whenever back button is pressed to force refresh the component cycle.
Should I go for it?
