### ISSUE TITLE
Making basic file structure

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#11]
### Description
The `src` folder in client needs to be refactored. The basic **component structure** is to be updated.

### Screenshots/testimonials
NA

**Comment by EmperorYP7** [comment]
May I start working on this @ankiiitraj?

**Comment by ankiiitraj** [comment]
go for it
also we need to create more of front-end issues for communtiy members to work upon

**Comment by ankiiitraj** [comment]
Closing this against PR #12
