### ISSUE TITLE
Creating Event Component

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/hg#112]
### Description
<write your description> This component will contain
 - Event table component

Event Table component will be passed these data as props
* Different events sorted by date as Running/Upcoming/Past Events (refer screenshot attached below).
* Pagination should be there.

### Concerned Folder
https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Event

### Assets 
https://drive.google.com/drive/folders/10TEVnDrYLLe8nbkYQLwT2qysBq65PPq-
### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

![event(2)](https://user-images.githubusercontent.com/59157988/94398267-dec8a600-0182-11eb-8017-ba0869051921.png)

**Comment by ankiiitraj** [comment]
suggestion: 
 - Create one component for the table and reuse it multiple times.
 - make a component form pagination
 - pass data as props to these components
