### ISSUE TITLE
Remove horizontal overflow in Error page

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#114]
### Description
The mobile version of the error page has a slight horizontal movement. This should be removed using CSS. For more info, check #89.

### Concerning Files/Folders

https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Error

### Screenshots/testimonials
![image](https://user-images.githubusercontent.com/62606998/94476528-3b14df80-01ee-11eb-930a-3995101c391e.png)

**Comment by ankiiitraj** [comment]
You can close this one, @hariom1625's commit on #89 fixed this issue

**Comment by ankiiitraj** [comment]
Closing this against #89
