### ISSUE TITLE
Creating Event table

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#115]
### Description
In ref to #112, Create a table component as described in the image.
Take dummy data and pass it through props.

### Screenshots/testimonials

![](https://user-images.githubusercontent.com/59157988/94398267-dec8a600-0182-11eb-8017-ba0869051921.png)

**Comment by EmperorYP7** [comment]
On it.

**Comment by EmperorYP7** [comment]
This might take me a while. Schedule's all messed up.

**Comment by EmperorYP7** [comment]
I am still on it. Hopefully, I'll get it done before the end of the month.
