### ISSUE TITLE
Create pagination component

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#116]
### Description

In ref to #112, Create a pagination component as described in the image.
Take dummy data and pass it through props.

### Screenshots/testimonials
![screenshot](https://user-images.githubusercontent.com/59157988/94398267-dec8a600-0182-11eb-8017-ba0869051921.png)

**Comment by EmperorYP7** [comment]
Instead of having START and END fields, we may have EVENT DATE and COMMUNITY here linking each row with the corresponding eventLink. Working on it.

**Comment by ankiiitraj** [comment]
This sounds cool! You can start working!
