### ISSUE TITLE
Adding Linkedin icon to Footer

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/hg#122]
### Description

* Add Linkedin icon to the footer. 
* Apply appropriate padding or margin for adjusting this extra icon on all screen sizes.
* HG Linkedin account link - https://www.linkedin.com/company/hgiiitranchi/
Note - Icon needs to be a static svg icon . Can be downloaded from https://fontawesome.com/icons?d=gallery&q=linkedin . 

### Concerning Folder
https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Footer

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>
NA

**Comment by SaravgiYash** [comment]
Hi, @tusharjain0022 I would like to work on this issue. Will create PR Tomorrow.

**Comment by SaravgiYash** [comment]
@ankiiitraj @tusharjain0022 I also need to create PR for the other two previous issues so I will create it Tomorrow. So "git pull --rebase upstream front-end" on those branches will be enough to align them with the current official repo?

**Comment by ankiiitraj** [comment]
yup you're correct

**Comment by tusharjain0022** [comment]
> Hi, @tusharjain0022 I would like to work on this issue. Will create PR Tomorrow.

Yes , @Yashs911 you can go ahead 👍
