### ISSUE TITLE
configuring webpack

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#124]
### Description

Webpack needs to be configured for having two different builds, one the public app and the other the admin app.

Having both of these in a single build will only increase the bundle size and increase the initial render time.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by EmperorYP7** [comment]
That would be a great optimisation for the app! 🤩

**Comment by ankiiitraj** [comment]
@Vishal19111999 Do you want to work on this?

**Comment by EmperorYP7** [comment]
We need to get this resolved before we officially release the website (v1.0).

**Comment by ankiiitraj** [comment]
I'll get back with the possible solution from the internet!

**Comment by EmperorYP7** [comment]
I think we should cover this in v2.0.

**Comment by vishalvibes** [comment]
@ankiiitraj can you give me more details on this? I would love to help

**Comment by ankiiitraj** [comment]
@Vishal19111999 What we want here is to create two different bundles one with the admin part and another the main app.

**Comment by ankiiitraj** [comment]
Dropping this because the admin panel might not be much of a burden on the bundle! What do you say?

**Comment by EmperorYP7** [comment]
Yes, I was thinking the same. But this might be reopened in the future.

**Comment by ankiiitraj** [comment]
closing for now!
