### ISSUE TITLE
Lorem Epsum

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#125]
### Description
- Collect the content for the landing page and update Lorem Epsum.
- Add the appropriate logos of different communities.
### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by NobodySS07** [comment]
May I add Content for ML community

**Comment by EmperorYP7** [comment]
Go ahead @NobodySS07!

**Comment by tusharjain0022** [comment]
I think placing appropriate logos for all the communities can be done in this issue itself . We'll be needing Logos of different communities for this.

**Comment by ankiiitraj** [comment]
@tusharjain0022 Go ahead and add the assets link in the description

**Comment by EmperorYP7** [comment]
This might require some writeups. I'll be sharing the contents for each section shortly.

**Comment by ankiiitraj** [comment]
This remains!

**Comment by ankiiitraj** [comment]
@EmperorYP7 provide the writeups here!

**Comment by EmperorYP7** [comment]
Completely forgot about this one! I'll get this done today.
