### ISSUE TITLE
Create a simple footer exclusively for Error Component

### ISSUE THREAD

**Issue by vishalvibes** [houseofgeeks/hg#126]
House of Geeks 404 Page should have an image in the footer, Only a single image that of the moon should be displayed.

**Comment by ankiiitraj** [comment]
@hariom1625 @tusharjain0022 Thoughts?

**Comment by tusharjain0022** [comment]
Currently that half cut moon like svg is looking a bit weird to me . Yes, if we'll display only the image of moon , it'll look more cleaner and nice. 

![error](https://user-images.githubusercontent.com/59157988/94657114-99d97680-031e-11eb-9d74-377a89a8f7fa.png)


Suggestion : I think that the Home link in the top left corner is also not necessary as we're having that in the navbar menu also.

**Comment by vishalvibes** [comment]
@tusharjain0022 I think you misunderstood the problem...I am talking about what happens when you scroll
although home button can be changed into an svg

**Comment by hariom1625** [comment]
Agreed, while scrolling the page it does look weird having that landed astronaut below the floating one over the moon, so for that, I think we can remove the image in the footer or the complete footer from the ERROR page and can keep the rest of the page as it is or instead of half-moon can have an image of a full moon.
Suggestions?

**Comment by ankiiitraj** [comment]
I agree with hariom, removing the footer images will make it cleaner!

**Comment by EmperorYP7** [comment]
> Agreed, while scrolling the page it does look weird having that landed astronaut below the floating one over the moon, so for that, I think we can remove the image in the footer or the complete footer from the ERROR page and can keep the rest of the page as it is or instead of half-moon can have an image of a full moon.
> Suggestions?

Yup. We should be removing the Footer component and add a custom footer especially for the error page. Although, I dont think any modification to the actual Footer component is necessary.

**Comment by tusharjain0022** [comment]
> > Agreed, while scrolling the page it does look weird having that landed astronaut below the floating one over the moon, so for that, I think we can remove the image in the footer or the complete footer from the ERROR page and can keep the rest of the page as it is or instead of half-moon can have an image of a full moon.
> > Suggestions?
> 
> Yup. We should be removing the Footer component and add a custom footer especially for the error page. Although, I dont think any modification to the actual Footer component is necessary.

Agreed 🙌

**Comment by tusharjain0022** [comment]
How About this , If the error page would render like this ?? 
![error-footer](https://user-images.githubusercontent.com/59157988/94947092-b6320a80-04fa-11eb-8692-91944009c90b.png)

**Comment by ankiiitraj** [comment]
@Vishal19111999 What do you say?

**Comment by vishalvibes** [comment]
Make the footer opaque

**Comment by tusharjain0022** [comment]
### 1 (After making the footer opaque)

![opaque](https://user-images.githubusercontent.com/59157988/94959983-bbe61b00-050f-11eb-829f-0d6f0468b75c.png)

I've tried few more things 😄 
### 2

![1](https://user-images.githubusercontent.com/59157988/94960355-5e9e9980-0510-11eb-88c9-1c9cfb72ae05.png)

### 3

![2](https://user-images.githubusercontent.com/59157988/94960057-d4563580-050f-11eb-9b53-d2cfd4474620.png)

**Comment by vishalvibes** [comment]
try pink color of hamburger

**Comment by tusharjain0022** [comment]
### 4

![pink](https://user-images.githubusercontent.com/59157988/94968264-3ae25000-051e-11eb-914c-f277ef369c72.png)


### 5

![dark-pink](https://user-images.githubusercontent.com/59157988/94968280-403f9a80-051e-11eb-8e73-9f74dcd02a5e.png)

**Comment by ankiiitraj** [comment]
@Vishal19111999  thoughts?

**Comment by ankiiitraj** [comment]
@tusharjain0022 We can finalize the 5th one! 🎉

**Comment by ankiiitraj** [comment]
BTW great work!

**Comment by EmperorYP7** [comment]
Great work @tusharjain0022 🤩

**Comment by EricLiclair** [comment]
![Error 404](https://user-images.githubusercontent.com/65639964/95010619-59dd0100-0648-11eb-82d2-bb976dd19171.png)


Looking closely, the 404 is supposed to have a gradient in the background, which would help the original mini footer in visibility, as well as the moon(planet) is to be centered a bit.

Also, the pink color `#EE2A7B` , in the footer will be very vibrant and would turn out to be over popping for the viewers.

What i propose is the original mini-footer, lying OVER the moon with a an opacity 95%.

_ignore the burger location_

**Comment by EricLiclair** [comment]
https://www.figma.com/file/NyIGhH5PhxbjfDf4DNmW55/House-of-Geeks?node-id=0%3A1

Here's the figma file.

**Comment by ankiiitraj** [comment]
@tusharjain0022 Interested in implementing this?

**Comment by tusharjain0022** [comment]
working on it !! 🙌
