### ISSUE TITLE
Event section on Landing page

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#129]
### Description
Does so much black space look good (see the screenshot)?
suggestion @Vishal19111999 @hariom1625 @tusharjain0022 @EmperorYP7 
### Screenshots/testimonials

![Screenshot from 2020-09-30 19-05-22](https://user-images.githubusercontent.com/48787278/94692376-19cc0480-0350-11eb-8e16-2303a39ce25d.png)

**Comment by hariom1625** [comment]
In which browser you are viewing this and the resolution of the screen?

**Comment by ankiiitraj** [comment]
FIrefox on ubuntu  and 1920X1080

**Comment by hariom1625** [comment]
Working fine in my firefox, Using Windows !!

**Comment by tusharjain0022** [comment]
It's happening at 1920 X 1080 .


![Screenshot (441)](https://user-images.githubusercontent.com/59157988/94725500-7db6f300-0379-11eb-819d-b61daebeee62.png)

**Comment by ankiiitraj** [comment]
Share the screenshot here! @hariom1625

**Comment by ankiiitraj** [comment]
anything that can be done @tusharjain0022 ?

**Comment by EmperorYP7** [comment]
This wasn't intended. It should be fixed.

**Comment by tusharjain0022** [comment]
I think media queries would solve this ,but first of all we need to figure out what is  causing this to happen

**Comment by ankiiitraj** [comment]
Mark it as an issue and give it a proper title anyone!

**Comment by hariom1625** [comment]
> Share the screenshot here! @hariom1625

Facing the same issue as mentioned in @tusharjain0022 screenshots, I think I misread the screen resolution before on my browser. My bad !!

Working on it !!

**Comment by hariom1625** [comment]
Shall I directly make the PR ? or should make an issue first?

**Comment by ankiiitraj** [comment]
Make an issue first!
