### ISSUE TITLE
Create design for WebDev team modal

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#141]
### Description

With reference to #98, provide a design for WebDev team modal to be displayed on the [hG website](https://houseofgeeks.netlify.app/). You should be following space theme for this. Kindly go through the website to get the design asthetics of the website and make this relevant to the present design. The modal should contain all the avatar/card of all the contributors of the project. You should also make a design for mobile version of the modal.

### Screenshots/testimonials
NA

**Comment by EmperorYP7** [comment]
Heads up @EricLiclair and @tusharjain0022!

**Comment by EricLiclair** [comment]
may i know the details to be included in the cards ?
Name, email? Github link? linkedin?

what else?

**Comment by ankiiitraj** [comment]
name, github, linkedin, email sounds good anything more @EmperorYP7 @hariom1625 @tusharjain0022

**Comment by EmperorYP7** [comment]
Yep that's all we need.

**Comment by ankiiitraj** [comment]
Do we've any progress here? @EricLiclair

**Comment by ankiiitraj** [comment]
We need progress on this @EmperorYP7

**Comment by tusharjain0022** [comment]
Based on the info that we can get from the GitHub contribution list [API](https://api.github.com/repos/houseofgeeks/hg/contributors) (Profile pic , profile link , repo link, no. of contributions) , I've created few designs for this issue.

# 1 
![Screenshot (8)](https://user-images.githubusercontent.com/59157988/96633866-8fcbe780-12ce-11eb-8d0a-3419e51e9d09.png)

![Screenshot (16)](https://user-images.githubusercontent.com/59157988/96635935-652f5e00-12d1-11eb-8d03-6e19b0fd0276.png)


# 2
![Screenshot (10)](https://user-images.githubusercontent.com/59157988/96633877-935f6e80-12ce-11eb-888a-4270bbab6fca.png)

![Screenshot (14)](https://user-images.githubusercontent.com/59157988/96635955-6a8ca880-12d1-11eb-99bd-74ec492eaf56.png)

**Comment by EmperorYP7** [comment]
I would prefer 1 over 2. What do you all think? @hariom1625 @ankiiitraj @Vishal19111999 @EricLiclair

**Comment by vishalvibes** [comment]
My vote goes to 2

**Comment by EmperorYP7** [comment]
> We need progress on this @EmperorYP7

Oops. missed it.

**Comment by ankiiitraj** [comment]
I will vote for 1 ~and on click on photo it should open my github profile in new tab.~
- On hover show my github username
- Below photo show my name
- Below that show icons of github, linkedin, mail or anything like facebook, insta

what do you say @Vishal19111999 @EmperorYP7 

Really liked your work @tusharjain0022 🎉

**Comment by tusharjain0022** [comment]
working on it 🙌
