### ISSUE TITLE
Footer icons are not centered properly

### ISSUE THREAD

**Issue by SaravgiYash** [houseofgeeks/hg#142]
### Description
Footer icons are not centered properly.

### Screenshots/testimonials
![hg](https://user-images.githubusercontent.com/64412143/94847537-56772900-0440-11eb-9a05-e6dac1c4567a.JPG)

**Comment by ankiiitraj** [comment]
@hariom1625 have a look!

**Comment by hariom1625** [comment]
The present layout isn't looking great to me making some changes !!
