### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#15]
### Description
Design a 404 Not Found Component
 - Be creative and make it look geeky and codey :p

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by sandesh-08** [comment]
I am interested in making this component . Should I start working on it

**Comment by EmperorYP7** [comment]
That's awesome @sandesh-08! 😄 Looking forward for your contribution.. 🙌🏻

**Comment by ankiiitraj** [comment]
closing against #30
