### ISSUE TITLE
add more sponsors

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#150]
### Description
Add outscal, Chef'sClub, IEEE and OSA as sponsors 

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by ankiiitraj** [comment]
@EmperorYP7 mention the assets link in the description
Add the logos too!

**Comment by EmperorYP7** [comment]
https://www.outscal.com/                             - Outscal
https://osa-iiitr.herokuapp.com/                    - OSA Student Chapter
https://iiitr-ieee-sb.netlify.app/                      - IEEE Student Branch
https://www.facebook.com/chefsClubIIITR/ - Chef's Club

**Comment by tusharjain0022** [comment]
Link for logos - https://drive.google.com/drive/folders/1_yKni7koI4dwnTfDFuhDI_a0RIrAsbRQ?usp=sharing

**Comment by tusharjain0022** [comment]
How we're gonna use the single sponsors component that we visit via navbar, any suggestions ?? @ankiiitraj @EmperorYP7 @hariom1625

**Comment by ankiiitraj** [comment]
I was thinking of having of reusing the same component there, if possible!

**Comment by hariom1625** [comment]
The issue with the present partners section is the opening of the sponsors page on clicking over the logo of any sponsor present within the Partners Section. If somehow we can disable the pointer action  over the sponsors logo in the sponsors page and having it enabled only on the partners section present on home page. Then the same component can be reused in the sponsors page as well.
Note: If we make the ```pointer-events: none``` this will also disable the hovering effect along with the active link so have to think of some other solution.

**Comment by EmperorYP7** [comment]
The only thing that needs to be changed is the link for every sponsor on homepage and sponsors page so, we can pass the links as props to the component everytime we call it.

**Comment by ankiiitraj** [comment]
Let me summarise, We want to achieve is just the branding of sponsors and no redirecting to their landing pages.

**Comment by hariom1625** [comment]
> Let me summarise, We want to achieve is just the branding of sponsors and no redirecting to their landing pages.

So, we can just remove the link tag. And reuse the Partners Section component on our sponsor's page.

PS: I have made some changes to the old code itself, not really a generic solution but I think it would work fine for this stage.
Shall I make the PR just for review purpose?

**Comment by EmperorYP7** [comment]
Go ahead @hariom1625!
