### ISSUE TITLE
Reduce astronaut size in mobile screen

### ISSUE THREAD

**Issue by SaravgiYash** [houseofgeeks/hg#151]
### Description
The astronaut is blocking the Hg name behind(Mobile screen)
@ankiiitraj @hariom1625 (Is this a valid issue?)
### Screenshots/testimonials
![hg1](https://user-images.githubusercontent.com/64412143/94947576-79b2de80-04fb-11eb-89a7-8b419f2c87d5.JPG)

**Comment by ankiiitraj** [comment]
is this intended? @EmperorYP7

**Comment by EmperorYP7** [comment]
Yes. It is intended.

**Comment by hariom1625** [comment]
It looks fine to me although  I think the HoG can be lifted a bit up revealing only the upper part of 'F', not the complete name.
Suggestions?
