### ISSUE TITLE
The animation on landing page should be removed.

### ISSUE THREAD

**Issue by EricLiclair** [houseofgeeks/hg#154]
### Description
Since we already have a great pre-loader, the dropping animation of the astronaut and the surface moving up, is not required.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>
Either, both the astronaut and surface be grouped into one and moved upwards
or, let both of them have no animation at all.

https://www.loom.com/share/e58be895f40442008755f535f56dfb1e

**Comment by EmperorYP7** [comment]
I think it creates a nice asthetic to the website.. We should definately reduce animations on the home page but removing them completely would not be quite as good as it is now.

**Comment by EricLiclair** [comment]
Agreed, that's why I added a solution to it: grouping the surface and the astronaut into one, and then the animation which slides up from bottom, also the z-index of the surface shout be kept below the `about us` section, as the surface while moving, overlays the about us section.

**Comment by hariom1625** [comment]
Want to give it a try @EricLiclair for the preview purpose?
I think it would be more fitting to implement the changes for visualization of the animation and then deciding which fits best for the website.

**Comment by ankiiitraj** [comment]
is this resolved? @EricLiclair @EmperorYP7 @hariom1625

**Comment by ankiiitraj** [comment]
Closing this! 
Seem resolved
