### ISSUE TITLE
Partners and Sponsors is not aligned properly

### ISSUE THREAD

**Issue by SaravgiYash** [houseofgeeks/hg#159]
### Description
Partners and Sponsors are not aligned properly.

### Screenshots/testimonials
![issue](https://user-images.githubusercontent.com/64412143/95242125-5efaa580-082c-11eb-8c25-5838b8dae1e7.JPG)

**Comment by EmperorYP7** [comment]
Whats the screen size for this?

**Comment by SaravgiYash** [comment]
@EmperorYP7 My laptop screen :) When I open inspect everything is aligned properly

![issue2](https://user-images.githubusercontent.com/64412143/95243021-a46ba280-082d-11eb-87b6-b2770f085704.JPG)

**Comment by tusharjain0022** [comment]
This issue seems to be present for screen width between 1500px to 1600px.

![Screenshot (475)](https://user-images.githubusercontent.com/59157988/95244194-4475fb80-082f-11eb-954e-98325810585d.png)

**Comment by SaravgiYash** [comment]
@tusharjain0022 @EmperorYP7  on line 128 changing min-width from 1600 to 1400 solves the issue but I don't know whether it will be an ideal fix 
![fix](https://user-images.githubusercontent.com/64412143/95247414-738e6c00-0833-11eb-975a-0af4baf26d1b.JPG)

Edit: the issue is between 1400px to 1600px

**Comment by SaravgiYash** [comment]
Hey, I would like to create a PR. According to me changing min-width:1400 will fix this issue.
