### ISSUE TITLE
Opening an issue for Octocon 2020 PR contest

### ISSUE THREAD

**Issue by vishalvibes** [houseofgeeks/hg#160]
This is a discussion for what issue can be opened for Octocon 2020 contribution contest

The issue should take like 3-5 hours and should be doable by even a beginner

Ideas are welcome!

**Comment by vishalvibes** [comment]
@ankiiitraj @Yashs911 @sanskarseth let's look into this

**Comment by sanskarseth** [comment]
Building reusable react components @Vishal19111999

**Comment by ankiiitraj** [comment]
Any ideas guys! @EmperorYP7 @tusharjain0022 @hariom1625

**Comment by vishalvibes** [comment]
@sanskarseth can we be more specific?

**Comment by sanskarseth** [comment]
@Vishal19111999 can you elaborate more on whether the issues will be linked to any of the existing repo. of HG or it will be completely different? Also whether it will we used further in any repo. or is it just for Octocon?

**Comment by vishalvibes** [comment]
It will just be like a normal issue for this repo

**Comment by EmperorYP7** [comment]
I think #116 #115 and #112 is quite apt for this. We need to get it done ASAP and it will take around 2-3 hours.

**Comment by vishalvibes** [comment]
Go ahead @EmperorYP7
