### ISSUE TITLE
Community page remembers previous page scroll position 

### ISSUE THREAD

**Issue by SaravgiYash** [houseofgeeks/hg#163]
### Description
When I open the community page it remembers the previous page scroll position.
### Screenshots/testimonials
![Capture](https://user-images.githubusercontent.com/64412143/95354641-43ea6d00-08e2-11eb-9d1f-2568685c40f0.JPG)

**Comment by hariom1625** [comment]
An alternate approach can be to open the targeted community in the new tab and I think than can be easily implemented.

**Comment by hariom1625** [comment]
An alternate approach/solution to this problem can be to open the targeted community in the new tab. And I think this might solve the issue.
Not the best way to tackle this issue, but if we already want to open the targeted community in the new tab then this issue won't arise.

**Comment by ankiiitraj** [comment]
another way is to write a high order component that will wrap the routes and using effectHook on page mount we can scroll it back to the top

**Comment by ankiiitraj** [comment]
Taking this up!
