### ISSUE TITLE
Add eventDate in the event model

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#167]
### Description

With reference to #116, backend should also be serving the event dates for it to be displayed on the event component. This should be defaulted to `Date.now()` and must be required for every event. We may also have the functionality of storing `endDate` to be more precise about event tenures etc. This is to be discussed further.

### Screenshots/testimonials
NA

**Comment by ankiiitraj** [comment]
didin't saw the discussion part 😅

**Comment by EmperorYP7** [comment]
No problem. I think we should implement the event page component as discussed in #116.
