### ISSUE TITLE
Footer component

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#17]
### Description

Making the footer according to the wireframe. Try to stick to bootstrap for styling. I think we should include the Contact Us section to the footer instead of having it in home page. What say?

### Concerning Folder

https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Footer

### Screenshots/testimonials

Footer wireframe

![Screenshot (339)](https://user-images.githubusercontent.com/62606998/92590263-8a37b680-f2b9-11ea-9927-6e962cbfe9f3.png)

**Comment by tusharjain0022** [comment]
Yes we can add Contact Us Section with the footer ,  For this we'll also have to change the background color code so that white fonts and icons can be visible.
May I work on this ??

**Comment by EmperorYP7** [comment]
Go ahead @tusharjain0022! Remember to make the relevant changes to the **front-end branch**. After you are done, create a PR that compares houseofgeeks:front-end to your front-end.

**Comment by tusharjain0022** [comment]
I've a suggestion , what if we design our footer like this(1st image) the HG logo will be visible  on min screen-size 768px Inplace of (2nd image) : 
![Screenshot (368)](https://user-images.githubusercontent.com/59157988/92638913-b1fa3f00-f2f8-11ea-81b9-25e70fc22c4e.png)
Inplace of this :
![Screenshot (367)](https://user-images.githubusercontent.com/59157988/92638973-ca6a5980-f2f8-11ea-8c2a-84db0bddb06a.png)

**Comment by EmperorYP7** [comment]
It is interesting. Sounds good to me! @ankiiitraj what do you say?

**Comment by ankiiitraj** [comment]
looks perfect go for it!

**Comment by tusharjain0022** [comment]
Working on it !!!

**Comment by ankiiitraj** [comment]
Closing this against #19
