### ISSUE TITLE
The fixed HG logo on the top can be given some padding for mobile view

### ISSUE THREAD

**Issue by SaravgiYash** [houseofgeeks/hg#171]
### Description
There is no padding for width<425px
I guess I should have done this in issue #102 

### Screenshots/testimonials
![hg](https://user-images.githubusercontent.com/64412143/96373312-5342a380-1189-11eb-86b1-e394c4842ff6.JPG)

**Comment by ankiiitraj** [comment]
if you want you can go for it @Yashs911
