### ISSUE TITLE
Create Design for Members Section

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/hg#173]
### Description
<write your description> Create a design for Members section . Kindly go through the website  and make this in accordance with the present theme. The members section should contain the cards/details of the members of particular community. You should also make a design for mobile version.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by EmperorYP7** [comment]
@hariom1625 want to go for it?

**Comment by hariom1625** [comment]
IMO we should ask @tusharjain0022 and @EricLiclair if they have any idea for the design of the member's section !!

Once the design will be finalized I will go for its implementation :-)

**Comment by EmperorYP7** [comment]
@EricLiclair was certainly working on one design. There was some confusion as to which members do we have to include to represent a community. We don't want to repeat members in the members page but we have to render them on two separate community page.

Apart from that, it is pretty straightforward.
