### ISSUE TITLE
making the Sponsors page

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#18]
### Description
I think we should use functional component and hooks rather than creating a class and the subsequent states. Lets stick to the wireframe for now. (suggestions are welcomed! 😄) You can add any creative modifications. Styling to be done using bootstrap classes. react-bootstrap is not preferred.

### Concerning Folder

https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Sponsors

### Screenshots/testimonials

WireFrame
![Screenshot (338)](https://user-images.githubusercontent.com/62606998/92686398-311e6000-f357-11ea-8fda-869cab5786f7.png)

**Comment by Abhayraj1707** [comment]
i m interested to work on this component should i start working on it ??

**Comment by EmperorYP7** [comment]
That's great @Abhayraj1707! Go for it.. 😄
