### ISSUE TITLE
Link to Code of Conduct is broken

### ISSUE THREAD

**Issue by Ampit** [houseofgeeks/hg#180]
### Description
<write your description> The link to Code of Conduct in the contributing.md is broken and displays not found.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

[Image1](https://user-images.githubusercontent.com/2737004/96837871-125ebf00-1415-11eb-8641-370c427c2847.jpg)

[Image2](https://user-images.githubusercontent.com/2737004/96837994-3de1a980-1415-11eb-9523-7c5d194bfaf7.jpg)

I can fix it if you would like ?

**Comment by ankiiitraj** [comment]
Go for it @Ampit
