### ISSUE TITLE
What's remaining?

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#186]
- ~Members section #173~ 
 - ~Individual community section #125~
 - ~Contributors section #141 #98~
 - ~Events table section #107 #112 #115 #116~

**v2.0**
- Set up an S3 bucket and link it to the back end.

Add if there's more!

**Comment by EmperorYP7** [comment]
I think we should assign every major issue to a maintainer and get it done ASAP. Improvements/enhancements will be done by making good first issues later on.
