### ISSUE TITLE
Minor Updates for Home Page

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/hg#195]
### Description-1
<write your description> I would suggest that here should be a `Know More` link below the events list in the notice corner on the home page that should redirect to the events page.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

![Screenshot (46)_LI](https://user-images.githubusercontent.com/59157988/97604869-313bf300-19cb-11eb-82ed-73f6551da84a.jpg)

### Description-2
<write your description> Heading/Title for the Communities Page should be there .

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

![Screenshot (47)](https://user-images.githubusercontent.com/59157988/97580286-553e0b00-19b0-11eb-8476-469ee24ca82e.png)

### Description-3
<write your description> Heading on the Home page should be uniform as currently some headings are centered and some not or are of different font size.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

![Screenshot (51)](https://user-images.githubusercontent.com/59157988/97580577-ba91fc00-19b0-11eb-938f-378abcc054ba.png)
![Screenshot (52)](https://user-images.githubusercontent.com/59157988/97580596-bd8cec80-19b0-11eb-8d33-1ca24b58634f.png)
![Screenshot (53)](https://user-images.githubusercontent.com/59157988/97580610-c087dd00-19b0-11eb-9ecb-9a8971c4da2a.png)

**Comment by ankiiitraj** [comment]
we can make separate issues for these and mark it as `good first issues` and can circulate these issues to class groups.
This will be a great place to get in for new contributors!
