### ISSUE TITLE
Headings on the home page should be uniform

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/hg#198]
### Description
<write your description> Heading on the Home page should be uniform as currently some headings are centered and some not or are of different font size.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

![Screenshot (51)](https://user-images.githubusercontent.com/59157988/97580577-ba91fc00-19b0-11eb-938f-378abcc054ba.png)
![Screenshot (52)](https://user-images.githubusercontent.com/59157988/97580596-bd8cec80-19b0-11eb-8d33-1ca24b58634f.png)
![Screenshot (53)](https://user-images.githubusercontent.com/59157988/97580610-c087dd00-19b0-11eb-9ecb-9a8971c4da2a.png)

**Comment by SaravgiYash** [comment]
@tusharjain0022 I would like to work on this issue.
