### ISSUE TITLE
Make frontend constistent

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#205]
### Description
In order to merge #192, changes need to be made accordingly on the frontend!

Priority or target 2.0?

**Comment by EmperorYP7** [comment]
I think the individual community pages should be priority for v1.0. This issue can be covered in the next iteration of the website.

**Comment by ankiiitraj** [comment]
let's fix this! Has now been delayed for a long time!

**Comment by EmperorYP7** [comment]
@hariom1625 @tusharjain0022 what say?
