### ISSUE TITLE
Render Members details of specific section in Community section also

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/hg#206]
### Description
<write your description>
Render Members details of specific section below the details of community.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

![Screenshot (58)_LI](https://user-images.githubusercontent.com/59157988/98241843-604cea00-1f20-11eb-9f31-78ded23baffb.jpg)

## Expected :
![screencapture-localhost-3000-electronics-iot-2020-11-05-18_07_14](https://user-images.githubusercontent.com/59157988/98242062-b752bf00-1f20-11eb-805c-e42c9d40c70b.png)

**Comment by ankiiitraj** [comment]
The Code from the members component can be reused here!

**Comment by tusharjain0022** [comment]
working on it 🙌
