### ISSUE TITLE
Change default display picture of members!

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#212]
The current DP doesn't look formal. Change the DP to something formal!

**Comment by ankiiitraj** [comment]
What do you say @EmperorYP7 @tusharjain0022?

**Comment by EmperorYP7** [comment]
Sure we can have it done only if we have decent enough pictures to replace the current ones with.

**Comment by ankiiitraj** [comment]
Nope, I'm talking about the default DP i.e this one here
![](https://houseofgeeks.netlify.app/images/reddit.png)

**Comment by EmperorYP7** [comment]
>Nope, I'm talking about the default

Yea. It looks really funny.

**Comment by tusharjain0022** [comment]
How about this image, Can we replace that with this one?

<img src="https://user-images.githubusercontent.com/59157988/102744615-1e7cd500-430f-11eb-9f74-a7e7c03572d9.jpg" alt="abstract-user-flat-4" width="200" height="200" />

source : https://freesvg.org/users-profile-icon

**Comment by ankiiitraj** [comment]
this looks good, what do you say @EmperorYP7  @hariom1625

**Comment by hariom1625** [comment]
> this looks good, what do you say @EmperorYP7 @hariom1625

The default DP does look a bit informal but it suits the website theme but since it is of Reddit mascot I don't know if we have the proper rights to use it therefore, IMO we should go with the one mentioned by @tusharjain0022 for now.

**Comment by EmperorYP7** [comment]
> How about this image, Can we replace that with this one?

@tusharjain0022 you might add this in #215.
