### ISSUE TITLE
UI breaking until the events have not arrived

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#213]
### Description
A fix is to give the events component a min height of some pixels!

I tried with 700px and it worked!

![Screenshot from 2020-12-16 12-36-11](https://user-images.githubusercontent.com/48787278/102316254-9cea1780-3f9b-11eb-9d73-986774d23734.png)

**Comment by EmperorYP7** [comment]
That's a quick fix. I think we should fix this before releasing

**Comment by tusharjain0022** [comment]
working on it 🙌

**Comment by EmperorYP7** [comment]
Closing against #215
