### ISSUE TITLE
Cleaning up the images folder

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#214]
### Description
<write your description> There is an obvious need to restructure or rather organise the [images folder](https://github.com/houseofgeeks/hg/tree/front-end/client/public/images) for better navigation and upgradability of members and other assets.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>
NA

**Comment by sb2356-iiitr** [comment]
I would like to contribute to this, will you please guide me through this? @EmperorYP7

**Comment by EmperorYP7** [comment]
@sb2356-iiitr for this, you need to restructure the [images folder](https://github.com/houseofgeeks/hg/tree/front-end/client/public/images) in such a way that members' images are in a directory called `Members` within the image directory (with further bifurcation of various communities), logos and various SVGs related to a specific page, say, the homepage could be moved to a directory named `HomePage` etc. You may propose a file structure which you think will be better for us to maintain.

**Comment by sb2356-iiitr** [comment]
Alright, thanks! I'm on it!

**Comment by sb2356-iiitr** [comment]
I am having some problems in cloning the rep into my PC....any help on this?
![image](https://user-images.githubusercontent.com/69338695/103170419-82e2eb80-485d-11eb-9862-018c102f412d.png)

**Comment by EmperorYP7** [comment]
> I am having some problems in cloning the rep into my PC....any help on this?

I think there's some problem with your internet connection. Also, keep in mind to not clone this in an existing git repository.

**Comment by sb2356-iiitr** [comment]
> > I am having some problems in cloning the rep into my PC....any help on this?
> 
> I think there's some problem with your internet connection. Also, keep in mind to not clone this in an existing git repository.

I don't know...my internet connection is fast enough....trying with GUI

**Comment by sb2356-iiitr** [comment]
I have made a pull request, requesting you to look into it.

**Comment by sb2356-iiitr** [comment]
Ok looks like the images now need to be relinked in the pages....can anyone help me with that?

**Comment by EmperorYP7** [comment]
> Ok looks like the images now need to be relinked in the pages....can anyone help me with that?

Sure, I've followed up on your PR's thread.

**Comment by sb2356-iiitr** [comment]
Made the necessary changes, please check.
![image](https://user-images.githubusercontent.com/69338695/103210399-fdc00b00-491e-11eb-88af-61bcc56409bd.png)
![image](https://user-images.githubusercontent.com/69338695/103210422-0adcfa00-491f-11eb-9438-e8b307830526.png)
![image](https://user-images.githubusercontent.com/69338695/103210438-13353500-491f-11eb-8cd7-20bff3c6de9d.png)
