### ISSUE TITLE
[Member] Set member image placeholder (fixed height)

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#216]
### Description
Add a default width and height to the wrapper of images. See the screenshot for the issue.

### Screenshots/testimonials
![Screenshot from 2020-12-26 19-57-30](https://user-images.githubusercontent.com/48787278/103153225-14e2e980-47b5-11eb-80f7-b7a00017c53b.png)

**Comment by EmperorYP7** [comment]
Should we address this in v2.0? or rather we can include this in #215 as a minor fix

**Comment by ankiiitraj** [comment]
let it remain open for first-time-contributors

**Comment by Gupta-Shrey855** [comment]
hello @ankiiitraj 
Is this issue is still opened?

**Comment by ankiiitraj** [comment]
@Gupta-Shrey855 yup that's still open

**Comment by AK-codingmaniac** [comment]
hello @EmperorYP7 is this issue still open?

**Comment by ankiiitraj** [comment]
@AK-codingmaniac this is open! feel free to pick it up

**Comment by EmperorYP7** [comment]
> hello @EmperorYP7 is this issue still open?

Yep. Go ahead!

**Comment by AK-codingmaniac** [comment]
@EmperorYP7 I have submited the PR regarding it.Please see to it
