### ISSUE TITLE
Making About Us Section

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/hg#22]
### Description
<write your description> Designing About Section in concerning folder . Images in about section should stack upon each other and on hover over specific image, it should come in front (its stack order becomes greater than the others on hover over it using z-index), refer to the wireframe or screenshot attached below for better clarification .Styling to be done using bootstrap classes. Lets stick to the wireframe for now. (suggestions are welcomed! 😄) You can add any creative modifications.

### Concerning Folder 
https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Home/AboutUs

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

![Screenshot (334)](https://user-images.githubusercontent.com/59157988/92798902-fce78580-f3d0-11ea-93d1-e4ed59269b7e.png)

**Comment by ankiiitraj** [comment]
closing against #40
