### ISSUE TITLE
Event page is breaking

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#220]
### Description
<write your description> The event page is not behaving as expected. Here, the Upcoming Events section is correctly rendered. But the Past Events section is blank. This shouldn't be the case.

### Screenshots/testimonials
<img width="1440" alt="Screenshot 2020-12-30 at 1 41 44 AM" src="https://user-images.githubusercontent.com/62606998/103312822-33aadf80-4a44-11eb-9d79-47371f8cefa7.png">

**Comment by EmperorYP7** [comment]
@ankiiitraj @tusharjain0022 @hariom1625 heads up!

**Comment by hariom1625** [comment]
On it!
