### ISSUE TITLE
Adding images and color code used in WireFrame

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/hg#23]
### Description
<write your description> Landing Page image and some other images along with Color Coding used in making Wireframe is not present or specified in the concerned folder in master branch

### Concerning Folder 
https://github.com/houseofgeeks/hg/tree/master/WireFrame

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by tusharjain0022** [comment]
May I create a PR for adding those images/text file containing color codes used to the master branch - WireFrame folder ???. So that others dont have to look for images and color codes that are being used while making the designs.

**Comment by EmperorYP7** [comment]
You may include that in #19

**Comment by ankiiitraj** [comment]
naah, make another PR, that PR has already filled up !

**Comment by ankiiitraj** [comment]
closing against #24
