### ISSUE TITLE
[Frontend] Modify event API call ☕ 

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#231]
### Description

Modify the API call on the AboutUs page to fetch only the first five events sorted from most recent to past.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>
<img width="1437" alt="Screenshot 2021-06-11 at 7 59 51 PM" src="https://user-images.githubusercontent.com/62606998/121702672-b950b200-caef-11eb-871d-c1feadcfb6d0.png">

**Comment by cod500** [comment]
Is this still available? Can I contribute and help the issue?

**Comment by EmperorYP7** [comment]
Yes, it is. Go ahead @cod500! :smile:

**Comment by cod500** [comment]
I examined the Json from the API. It seems as though it is already sorted from most recent upcoming event to past events at the API level so all this needs is a limit of 5 on the front end. Let me know if I am interpreting this incorrectly.

**Comment by SrijanSriv** [comment]
Hi!

This has been implemented I think.

**Comment by EmperorYP7** [comment]
> Hi!
> 
> This has been implemented I think.

Yep. youre right @SrijanSriv. Closing this against #233
