### ISSUE TITLE
[Admin] List of events not visible

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#232]
### Description

Modify the API call in Admin page to fix this error.

### Screenshots/testimonials

<img width="1440" alt="Screenshot 2021-06-17 at 2 07 55 AM" src="https://user-images.githubusercontent.com/62606998/122290492-6b81e280-cf11-11eb-966b-71f73d0bb5cc.png">

**Comment by Nerfi** [comment]
hey there , is this still available ?
would like to give it a go !

**Comment by EmperorYP7** [comment]
Sure! Go ahead :smile:

**Comment by Nerfi** [comment]
hey, can you give me a explanation of what do you really need/want in here ?

**Comment by Nerfi** [comment]
Hey there, the description is not really clear to me, however I think that I sort out the problem we have.
I could render the list of 10 events that useEffect is calling throught this api get request `.get(`${process.env.REACT_APP_API || ''}/event/`)`, is this what you want it? 
Also, is there a way I can get the admin credentials ? I logged out and now I can not log in again 

thanks

**Comment by SrijanSriv** [comment]
This issue was just changing `/events/all` to `/events`. Will make a pr soon.
