### ISSUE TITLE
[Members] Fix the CSS for certain Communities

### ISSUE THREAD

**Issue by SrijanSriv** [houseofgeeks/hg#235]
### Description
You would notice that there is a certain way of ordering members such that Community Heads are above the Coordinators and same level members are, well, at the same height. This is not the case with Competitive Coding Community.  Try to fix this.

### Screenshots/testimonials
<img src = "https://user-images.githubusercontent.com/79690889/132098361-fad1f6bc-c39d-464d-bb58-df727c72c898.png" width = "500px" height = "400px">
 <img src = "https://user-images.githubusercontent.com/79690889/132098483-82c3c55d-9a11-40c4-bac3-6cddb455857d.png" width = "500px">

**Comment by SrijanSriv** [comment]
I tried to tackle this but to no avail. I feel like this is a good first issue though.

**Comment by EmperorYP7** [comment]
>  I feel like this is a good first issue though.

Yes, it is. Would you like to take this up?

**Comment by SrijanSriv** [comment]
> > I feel like this is a good first issue though.
> 
> Yes, it is. Would you like to take this up?

Naah I discussed with a few who rather would. I didn't in my own pr cuz I can't.

**Comment by himanshu007-creator** [comment]
Hi, I would like to work on this issue, but when I opened the <a href ="https://houseofgeeks.netlify.app/members">member's page</a>, i was unable to spot the issue, maybe I am looking elsewhere, please help me out here

**Comment by EmperorYP7** [comment]
> Hi, I would like to work on this issue, but when I opened the [member's page](https://houseofgeeks.netlify.app/members), i was unable to spot the issue, maybe I am looking elsewhere, please help me out here

@himanshu007-creator apparently, the changes merged with #234 are not reflected in the main deployment of the website.

For reference look at [this comment](https://github.com/houseofgeeks/hg/pull/234#issuecomment-912990707).

**Comment by abhishekrathi16** [comment]
I have completed working on the issue, will create a PR for the same asap.
