### ISSUE TITLE
[front-end ] Replace "WebDev Team House of Geeks" text in footer

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/hg#245]
### Description
- The text "WebDev Team House of Geeks" is misleading as it's a modal for a list of contributors of this repo.
- Styling should signify that it's clickable.
- Replacing Text should be "Contributors" or "Become a Contributor" etc.

### Screenshots/testimonials
![Screenshot from 2021-10-30 23-53-31](https://user-images.githubusercontent.com/59157988/139554220-b1196e2b-6ec2-4fef-b39c-d6f2389a87ea.png)

**Comment by tusharjain0022** [comment]
CC: @EmperorYP7 @SrijanSriv

**Comment by AK-codingmaniac** [comment]
@tusharjain0022 I would like to take this issue

**Comment by tusharjain0022** [comment]
yeah, you can go ahead @AK-codingmaniac.

**Comment by AK-codingmaniac** [comment]
@tusharjain0022 @EmperorYP7 I have created a PR regarding it.Please review it
