### ISSUE TITLE
Expansion of Home page

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#25]
### Description

Home page is going to have multiple sub-components for which the current file structure and the wireframe is insufficient. We'll also be having a notice board which would be retriving data from the API. #22 and forth coming issues will also be based on these sub-components. It would be better if we make the file structure for the same now.

### Concerning Folder

https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Home

### Screenshots/testimonials
NA

**Comment by EmperorYP7** [comment]
I am on it now! Will create a PR for this once #21 is merged.

**Comment by ankiiitraj** [comment]
Closing against #28
