### ISSUE TITLE
Typo in Nav Menu

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/hg#256]
### Description
- Instead of 'Event', it should be 'Events' (refer Screenshot attached below)

### Steps to Reproduce 
- visit https://houseofgeeks.netlify.app/
- open navbar menu

### Screenshots/testimonials

![Screenshot from 2022-05-17 01-01-40](https://user-images.githubusercontent.com/59157988/168668505-10ce9039-6a64-4c4a-965a-964c66eacd08.png)

**Comment by KhanyaMateta** [comment]
I'm interested in helping... How can I get access to the code?

**Comment by Milziade** [comment]
Pull request sent

**Comment by BrendonW250** [comment]
Hi I have also sent my pull request
