### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by hariom1625** [houseofgeeks/hg#26]
### Description
On switching tab on Navbar and then reloading the page the URL seems to be broken and doesn't render the page as specified in the URL.
### Screenshots/testimonials
![Screenshot (161)](https://user-images.githubusercontent.com/66957239/92936305-8fd2ff00-f467-11ea-8a44-cb60e7861f13.png)

**Comment by hariom1625** [comment]
On it.

**Comment by ankiiitraj** [comment]
Closing against #31
