### ISSUE TITLE
Hamburger isn't a good ui element for webview

### ISSUE THREAD

**Issue by SrijanSriv** [houseofgeeks/hg#275]
### Description
Normal navigation is missing. Clicking on hamburger icon and viewing different navigation option is used where we have less space available on the screen.

### Screenshots/testimonials
![image](https://user-images.githubusercontent.com/79690889/218755870-0a814f02-023a-4ca2-9857-061f75583998.png)

**Comment by tilltonystark** [comment]
Can we discuss what can we show on the navigation bar of HG v2.0?

**Comment by SrijanSriv** [comment]
These are the few sections that we are planning to came up with in hg v2.0
- Home
- Resources
- Projects
- Blogs
- About

**Comment by tilltonystark** [comment]
Here is the simple lo-fi wireframe of the nav bar that I came up with. 
![image](https://user-images.githubusercontent.com/89836460/218760568-404a28d8-c7a1-4205-a4dc-dd3d1f47d135.png)

We can implement colors and icons once we create a style guide for hg v2.0

**Comment by SrijanSriv** [comment]
As of now it looks good to me. We'll make this changes when we update the website. 

Thank you
