### ISSUE TITLE
Event Schema and routes

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#29]
### Description

Create event schema for storing event data in MongoDB with mongoose and relevant API routes for basic CRUD (Create-Read-Update-Delete) operations. Event data should have a title, a short description, a long description, an image path, event date, Google Calendar link and Google maps link.

### Concerning Folder

https://github.com/houseofgeeks/hg/tree/back-end/backend/models
https://github.com/houseofgeeks/hg/tree/back-end/backend/routes

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

NA

**Comment by ankiiitraj** [comment]
Working!

**Comment by ankiiitraj** [comment]
Closing against #50
