### ISSUE TITLE
Create Notice Modal 

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#36]
### Description
<write your description> Create notice modal and use dummy text to test

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>
NA

**Comment by sj00coder** [comment]
Hello sir I want to work on it.

**Comment by ankiiitraj** [comment]
Hi, @sj00coder You can go ahead and work on it. Assigning this to you!

**Comment by sj00coder** [comment]
Sir you want to open the modal on window load or a specific button for triggering modal.
If button, then please tell the position of button.
![image](https://user-images.githubusercontent.com/65244030/93293512-c3b27980-f805-11ea-876d-dbb31a3ec9c4.png)

**Comment by ankiiitraj** [comment]
won't be like that . . . it will be much more like check iiitranchi.ac.in notice . . . and try to make it awesome!

**Comment by ankiiitraj** [comment]
No longer required closing this
