### ISSUE TITLE
Add community section.

### ISSUE THREAD

**Issue by sanskarseth** [houseofgeeks/hg#38]
Design the community section as the wireframe below.
![Screenshot (335)](https://user-images.githubusercontent.com/55178412/93182497-6233d180-f757-11ea-9115-e5841eea380d.png)

**Comment by sj00coder** [comment]
Hello sir, I want to work on it.

**Comment by deepti-iiitr** [comment]
I am interested in working on this. Can I start?

**Comment by ankiiitraj** [comment]
You both can collaborate on this and start working. Assigned to both of you

**Comment by ankiiitraj** [comment]
Closing against #48
