### ISSUE TITLE
Create admin dashboard

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#41]
### Description
<write your description> 

- Admin Dashboard will have a card with admin details 
and rest of the admin-functionalities components will reside in this component
### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by sanskarseth** [comment]
Working on this.

**Comment by EmperorYP7** [comment]
I dont think this should be handled by the front-end. We should have view engine (maybe ejs?) set up for the whole admin system which will be configured in back-end.

**Comment by ankiiitraj** [comment]
Yes I agree this is not clever to send the admin build with the app, meaningless increase in build size
We're planning is sending another react app on /admin route but for development's sake, it can be built upon the same react app.
suggestions?

**Comment by EmperorYP7** [comment]
Well then we have a plathora of admin console templates available for react. Great!

**Comment by ankiiitraj** [comment]
let just not go for templates now as there are community members who can implement these to learn and enhance their skills!
If we'll be tight on the schedule we can implement those.
Sounds Good?

**Comment by EmperorYP7** [comment]
Perfect :+1:
