### ISSUE TITLE
Create admin events controller component

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#43]
### Description
<write your description> 
This component will contain

- Different events posted.
- Admin should be able to create an event 
- Admin should be able to edit or delete any event 
- Pagination should be there.
 

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by sanskarseth** [comment]
I will like to build all the admin dashboard components.

**Comment by EmperorYP7** [comment]
The front-end doesn't treat events and notices to be separate entities. I guess, we should drop notice altogether. Or rather, rename notice as event on the API side.

**Comment by ankiiitraj** [comment]
I was thinking the same, this needs discussion!

**Comment by tusharjain0022** [comment]
Suggestion : I've a basic layout design for the event component where details of all the events are to be displayed.
Note - It's just a blueprint so color is set to default.

![event-page](https://user-images.githubusercontent.com/59157988/94360044-3e15b000-00c8-11eb-8ba1-12e548a2e2d4.png)

![single](https://user-images.githubusercontent.com/59157988/94360200-4c180080-00c9-11eb-901d-d52d46b98197.jpg)
