### ISSUE TITLE
Create admin login page

### ISSUE THREAD

**Issue by sanskarseth** [houseofgeeks/hg#45]
### Description

Create an admin login page consisting of username and password in which username will already be there in a dropdown list and admin would only require to enter the password.

### Screenshots/testimonials
NA

**Comment by sanskarseth** [comment]
Working on this.

**Comment by sanskarseth** [comment]
Please reassign me, i have unassigned by mistake.

**Comment by sanskarseth** [comment]
![Screenshot from 2020-09-18 23-58-18](https://user-images.githubusercontent.com/55178412/93632546-1d37c580-fa0b-11ea-91a3-ac640dd10f8f.png)
Any Suggestions or its fine...

**Comment by EmperorYP7** [comment]
This looks cool to me @sanskarseth! 🤩

**Comment by ankiiitraj** [comment]
Closing against #58
