### ISSUE TITLE
Remaking the Navbar

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#49]
### Description
The overall theme of the website has been changed and to match the esthetics of the website, we need to remake the navbar. The navbar should always be in a hamburger fashion in the left hand side of the viewport at all sizes. When we click on the hamburger, it should trigger an animation which fills up all of the screen with `background: #000018;`

### Screenshots/testimonials

Here's the **complete wireframe**:

https://www.figma.com/proto/NyIGhH5PhxbjfDf4DNmW55/House-of-Geeks?node-id=4%3A0&viewport=867%2C-224%2C0.5157824158668518&scaling=scale-down-width

![image](https://user-images.githubusercontent.com/62606998/93580668-b9d37680-f9bd-11ea-945b-5a039e3f5cc7.png)
![image](https://user-images.githubusercontent.com/62606998/93582492-2ea7b000-f9c0-11ea-81f3-91b280b7ff2b.png)

### Concerning Folder/Files

https://github.com/houseofgeeks/hg/blob/front-end/client/src/App.js (Remember to uncomment the Navbar component)
https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Navbar

**Comment by ankiiitraj** [comment]
looks impressive!

**Comment by EmperorYP7** [comment]
Kudos to @EricLiclair! 🙌🏻

**Comment by tusharjain0022** [comment]
May I start working on this issue ?

**Comment by ankiiitraj** [comment]
Assigning this to you @tusharjain0022

**Comment by ankiiitraj** [comment]
closing this against #54
