### ISSUE TITLE
Remaking About Us section

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#56]
### Description
Follow the provided wireframe and construct a graphically rich about us section using bootstrap and custom CSS. Achieve proper positioning and responsiveness then create a PR where we discuss about animations and see the deployment in real time.

### Screenshots/testimonials

The complete wireframe:
https://www.figma.com/proto/NyIGhH5PhxbjfDf4DNmW55/House-of-Geeks?node-id=4%3A0&scaling=min-zoom

![image](https://user-images.githubusercontent.com/62606998/93690892-87c82e80-fafb-11ea-9cf3-41095dc893d3.png)
![image](https://user-images.githubusercontent.com/62606998/93690900-a2020c80-fafb-11ea-8b56-3a85585d8636.png)

### Concerning Files/Folders

https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Home/AboutUs

### Assets

https://drive.google.com/drive/folders/10TEVnDrYLLe8nbkYQLwT2qysBq65PPq-?usp=sharing

**Comment by EmperorYP7** [comment]
I am working on this.

**Comment by ankiiitraj** [comment]
Assigning this to you @EmperorYP7

**Comment by ankiiitraj** [comment]
closing against #62
