### ISSUE TITLE
Remaking the NotFound (Error) page

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#57]
### Description

Remake the NotFound page according to the new wireframe provided using bootstrap and custom CSS. This should be made responsive. I'll be sending the assets for this page once someone is assigned.

### Screenshots/testimonials

![Desktop - 2](https://user-images.githubusercontent.com/62606998/93691521-f0b3a480-fb03-11ea-9d56-41c1e9ea6509.jpg)

### Concerning Files/Folders

https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Error

**Comment by Abhayraj1707** [comment]
I will try to implement this ! Please provide me assets.

**Comment by EmperorYP7** [comment]
https://drive.google.com/drive/folders/1-oAafqapEnkVtqu6fACBHLWq_aMNIvkF?usp=sharing
There you go @Abhayraj1707!
