### ISSUE TITLE
Refacetoring the Partners section on Landing page

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#63]
### Description
<write your description>

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by ankiiitraj** [comment]
@EmperorYP7  Add the required wireframe to the description!

**Comment by EmperorYP7** [comment]
### WireFrame

https://www.figma.com/file/WKIfra7Dxh033gwNoRikh6/House-of-Geeks-Copy?node-id=0%3A1

### Wireframe for mobile

https://www.figma.com/proto/NyIGhH5PhxbjfDf4DNmW55/House-of-Geeks?node-id=107%3A74&scaling=min-zoom

![image](https://user-images.githubusercontent.com/62606998/93864973-47c3a000-fce3-11ea-9fb4-50440ab10e06.png)

**Comment by hariom1625** [comment]
Working on it.

**Comment by ankiiitraj** [comment]
Closing against #75 
Thanks @hariom1625 for the PR
