### ISSUE TITLE
Making the Community Section

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/hg#64]
### Description
In continuation to #56 and #62, we should be aiming to make the community section in the Home component ASAP. This component will also be rendered when the user taps/clicks on Community from the Navbar although in this case, Community should be the only component being rendered. Try sticking to the wireframe as close as possible using bootstrap and custom CSS. Hovering effects are also expected but, as soon as you achieve the correct orientation according to wireframe, draft a PR so that it can be monitored.

### Screenshots/testimonials
**WireFrame** : https://www.figma.com/file/WKIfra7Dxh033gwNoRikh6/House-of-Geeks-Copy?node-id=0%3A1

For screens larger than 426 px, try to keep it like this..
![image](https://user-images.githubusercontent.com/62606998/93863054-a5a2b880-fce0-11ea-97dd-b409bcc86e69.png)

For less than 426px, go for the design given in the wireframe above.
![image](https://user-images.githubusercontent.com/62606998/93865628-36c75e80-fce4-11ea-84a9-59e5ab99026f.png)

### Concerning Files/Folders

https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Home/CommunitySection
https://github.com/houseofgeeks/hg/tree/front-end/client/src/components/Community

**Comment by EmperorYP7** [comment]
Seems like no one is taking this up. So, I am working on this.

**Comment by hariom1625** [comment]
> Seems like no one is taking this up. So, I am working on this.

I thought to start working on it after finishing partners section, Let me know if stuck somewhere.
Besides this What action will be performed after clicking on 'Know More'.

**Comment by EmperorYP7** [comment]
Alright @hariom1625.
https://www.figma.com/file/q2CSK29UovyGQtUOc9BP4v/House-of-Geeks-Copy?node-id=0%3A1
Here you can see in 'Desktop-4' screen what should be rendered after clicking through 'Know more' on community card.
![image](https://user-images.githubusercontent.com/62606998/93974829-08a15780-fd94-11ea-8206-0af5499a7230.png)
