### ISSUE TITLE
hosting the backend on herouku

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#66]
### Description
<write your description>
For better CI, hosting the backed for data is important and the current best alt is Heroku.

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by EmperorYP7** [comment]
Yes. For now we can go for Heroku for CI. #69 #68 had it clear. Are we up and running on heroku?

**Comment by ankiiitraj** [comment]
Backend is up on Heroku now just a pull needed! Currently running on my fork!

**Comment by ankiiitraj** [comment]
yea! perfectly working
Heroku and monogo remote with netlify 
Another goal setup a Public Cloud Storage ex. Aws S3 bucket for images and pdfs

**Comment by EmperorYP7** [comment]
Sounds like a new issue to me. But I think we should proceed with that now.
