### ISSUE TITLE
Creating a remote MongoDB

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#67]
### Description
<write your description>
For better CI, Current alternative for free MongoDB, suggestions?

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>

**Comment by EmperorYP7** [comment]
I've no experience in setting up CI for this. But, free DB is nice. Not the snappiest but nice.

**Comment by ankiiitraj** [comment]
So we are now using mongo atlas!

**Comment by EmperorYP7** [comment]
> So we are now using mongo atlas!

Wohooo! 🥳

**Comment by ankiiitraj** [comment]
This has been hosted on https://cloud.mongodb.com with imantiqueroy@gmail.com
