### ISSUE TITLE
Hg logo looks messed

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#77]
### Description
While scrolling in smaller screens the Hg logo gets overlapped by letters which looks bad!
My initial thoughts, we can make a solid background on top which will be fixed and the Hg logo will be there along with the hamburger

suggestions?

### Screenshots/testimonials
![Screenshot from 2020-09-23 12-58-14](https://user-images.githubusercontent.com/48787278/93980875-d5af9180-fd9c-11ea-8214-724c274a2fab.png)

**Comment by EmperorYP7** [comment]
I couldn't find this problem while debugging. What are the dimensions of this viewport?

**Comment by ankiiitraj** [comment]
This is an IPhone XR on Firefox

**Comment by vishalvibes** [comment]
Why don't we just remove hg logo from the top...why write it 2 times?

**Comment by ankiiitraj** [comment]
@EmperorYP7 clear it out here!

**Comment by EmperorYP7** [comment]
> Why don't we just remove hg logo from the top...why write it 2 times?

That's a thought. But what if we keep it fixed at a superior z-index for the entire lifecycle (or view-cycle) of the website?

**Comment by tusharjain0022** [comment]
@ankiiitraj @EmperorYP7  Checkout the deployed site link on mobile browsers - https://houseofgeeks.netlify.app , I think this issue isn't there and only persist while we are checking this via chrome developers tool on Laptop/PC. Seems like Parallax Scrolling Effect isn't working on mobile.

![WhatsApp Video 2020-09-26 at 5 51 12 PM](https://user-images.githubusercontent.com/59157988/94340770-e45aaa80-0021-11eb-8531-f0a80d4beff6.gif)

**Comment by EmperorYP7** [comment]
![Screenshot_20200926-173953191.jpg](https://user-images.githubusercontent.com/62606998/94340425-4d8cee80-001f-11eb-93e7-fcee328af1c8.jpg)

Working for me though..

**Comment by ankiiitraj** [comment]
> @ankiiitraj @EmperorYP7 Checkout the deployed site link on mobile browsers - https://houseofgeeks.netlify.app , I think this issue isn't there and only persist while we are checking this via chrome developers tool on Laptop/PC. Seems like Parallax Scrolling Effect isn't working on mobile.
> 
> ![WhatsApp Video 2020-09-26 at 5 51 12 PM](https://user-images.githubusercontent.com/59157988/94340770-e45aaa80-0021-11eb-8531-f0a80d4beff6.gif)

this is happening in with which browser!
I thought the planet and logo were fixed at that place!
Seem new issue to me

**Comment by tusharjain0022** [comment]
> > @ankiiitraj @EmperorYP7 Checkout the deployed site link on mobile browsers - https://houseofgeeks.netlify.app , I think this issue isn't there and only persist while we are checking this via chrome developers tool on Laptop/PC. Seems like Parallax Scrolling Effect isn't working on mobile.
> > ![WhatsApp Video 2020-09-26 at 5 51 12 PM](https://user-images.githubusercontent.com/59157988/94340770-e45aaa80-0021-11eb-8531-f0a80d4beff6.gif)
> 
> this is happening in with which browser!
> I thought the planet and logo were fixed at that place!
> Seem new issue to me

This is on my Redmi4 chrome browser.

**Comment by ankiiitraj** [comment]
so what are we doing now on this one? suggestions?

**Comment by EmperorYP7** [comment]
Tried to make it fixed for the entire website. It didn't look good at first. Still trying to find a way around it.

**Comment by tusharjain0022** [comment]
Suggestion : What if we remove the parallax scrolling effect on screen width less than 427px explicitly as it is happening in my mobile browser. Can this be a solution to this problem?? @ankiiitraj  @hariom1625  @EmperorYP7 👀

**Comment by ankiiitraj** [comment]
That sounds good! So are we talking about fixing the logo with some background or what?

**Comment by tusharjain0022** [comment]
After removing the parallax effect for small devices the landing page will render like this on all small devices (<427px) :
![WhatsApp Video 2020-09-26 at 5 51 12 PM](https://user-images.githubusercontent.com/59157988/95000679-92e18b00-05e0-11eb-8e58-0066c53299f6.gif)

**Comment by ankiiitraj** [comment]
This looks good to me! We can move ahead with the implementation 🥳

**Comment by tusharjain0022** [comment]
Working on it! 🙌
