### ISSUE TITLE
Set a favicon

### ISSUE THREAD

**Issue by vishalvibes** [houseofgeeks/hg#87]
I have made a temporary favicon.
Have a look

![android-chrome-512x512](https://user-images.githubusercontent.com/29145212/94252083-147e4c80-ff41-11ea-955e-78f43acd5f76.png)

**Comment by ankiiitraj** [comment]
Looks good to me! :tada:
Watch this @tusharjain0022 @hariom1625 @EmperorYP7

**Comment by EmperorYP7** [comment]
That's a hot pink! I like this one. :fire:

**Comment by ankiiitraj** [comment]
@Vishal19111999 Go ahead and set this one as the favicon, btw if you have the SVG it would be more preferable!

**Comment by tusharjain0022** [comment]
Looks Perfect to me! 🤩

**Comment by hariom1625** [comment]
Looks cool !! 🙌

**Comment by vishalvibes** [comment]
This issue is open for beginners
If anyone wants to contribute, he/she can inform us in the comments and start working

**Comment by deepti-iiitr** [comment]
I want to work on this.

**Comment by ankiiitraj** [comment]
go ahead! 🎉 
Here is the icon https://drive.google.com/drive/folders/1rlOg72pYybjSs626hdv9OcJ0odSA_MGg?usp=sharing
