### ISSUE TITLE
Update the Readme with Contributirs

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#88]
### Description
Update the contributor's section of Readme.
Requirement: Every contributor's should be there and clicking on it should open his Github profile.

### Screenshots/testimonials

![Screenshot from 2020-09-25 15-59-58](https://user-images.githubusercontent.com/48787278/94257030-51017680-ff48-11ea-993d-81f92171defe.png)

**Comment by hariom1625** [comment]
I would like to work on it.

**Comment by EmperorYP7** [comment]
Go ahead @hariom1625! 🙌🏻

**Comment by ankiiitraj** [comment]
Remember that the collaborators section in this repository don't show contributors from the front-end branch and only show from the master branch.
I am changing the default branch to front-end
