### ISSUE TITLE
Remove sponsors name

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#95]
### Description
The sponsor's name is not required below its logo. Instead, on-hover make the label as the name of the sponsor.
Also, make the image as a link that will open the sponsor's page in the new tab.

### Screenshots/testimonials

![Screenshot from 2020-09-26 12-15-11](https://user-images.githubusercontent.com/48787278/94332336-f4f32c80-fff1-11ea-8ec0-7e428662b07a.png)

**Comment by ankiiitraj** [comment]
Hi @hariom1625, are you interested in this!

**Comment by hariom1625** [comment]
Yeah, sure :-)

**Comment by ankiiitraj** [comment]
what's your suggestion @hariom1625 @tusharjain0022 @EmperorYP7

**Comment by hariom1625** [comment]
I had a doubt, we will be having a single sponsor's page ? So for redirection every logo of partners section should redirect to a single sponsor page or each logo will redirect to the sponsor page of that particular sponsor?

**Comment by ankiiitraj** [comment]
> I had a doubt, we will be having a single sponsor's page ? So for redirection every logo of partners section should redirect to a single sponsor page or each logo will redirect to the sponsor page of that particular sponsor?

Redirecting them to a single page appears more apealing

**Comment by ankiiitraj** [comment]
![Screenshot from 2020-09-27 02-39-47](https://user-images.githubusercontent.com/48787278/94351313-19dcb380-0075-11eb-95e0-c9e15f0943fc.png)
This looks cool too!

**Comment by hariom1625** [comment]
Looks cool !! But for this, we will need to design the logos to suit with the theme of our website.

**Comment by ankiiitraj** [comment]
That's correct let us stick to the current one!
