### ISSUE TITLE
Create Web Team Modal

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#98]
### Description
Create Modal box for Web team

### Screenshots/testimonials

I'll update it with an example

**Comment by EmperorYP7** [comment]
How should we approach this? 🤔 @hariom1625 we can have something out of the bot's API.

**Comment by hariom1625** [comment]
> How should we approach this? 🤔 @hariom1625 we can have something out of the bot's API.

We can use the GitHub API to get the contributors list in the JSON format easily and then parse through all the contributors GitHub URL and names.
This is the API link for hg repo contributors : https://api.github.com/repos/houseofgeeks/hg/contributors

**Comment by EmperorYP7** [comment]
That's great! 🙌🏻  We would be needing a design for this..

**Comment by ankiiitraj** [comment]
@EmperorYP7, Add an issue for the same

**Comment by EmperorYP7** [comment]
> @EmperorYP7, Add an issue for the same

For the design?

**Comment by ankiiitraj** [comment]
Yup and mention this issue there for ref
