### ISSUE TITLE
Add text to preloader

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#99]
### Description
Add text `Loading . . .` to the preloader.

Ask doubts in the comments!

### Screenshots/testimonials
N/A

**Comment by SaravgiYash** [comment]
@ankiiitraj I would like to work on this. Could you please assign me this task.
And can you please elaborate exactly which file I need to change?

**Comment by ankiiitraj** [comment]
The files is here https://github.com/houseofgeeks/hg/blob/front-end/client/public/index.html
If you see the preloader, only the rocket appears. 
We can put a text showing Loading just below the rocket to make it more intutive
